apiVersion: v1
kind: ServiceAccount
metadata:
  name: sentinelai-sa
  namespace: sentinelai
  labels:
    app.kubernetes.io/name: sentinelai
    app.kubernetes.io/component: serviceaccount
automountServiceAccountToken: false
